<a href="https://colab.research.google.com/github/shareefat/folio/blob/main/DAV_DAY_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DAV**---> (DATA ANALYSIS AND VISUALIZATION)
#NUMPY (ARRAY(NUMBERS)))
#PANDAS (DATA ANALYSIS)
#MATPLOTLIB, SEA BORN (VISUALIZATION)

In [6]:
import numpy as np
a=np.array([1,2,.8,2+7j,"PGDDM44"])
a

array(['1', '2', '0.8', '(2+7j)', 'PGDDM44'], dtype='<U64')

In [8]:
#only with interger values and float values
import numpy as np
a=np.array([13,4,53,])
a



array([13,  4, 53])

In [9]:
#Dimensions
a.ndim

1

In [10]:
#no:of rows and colmns
a.shape

(3,)

In [23]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b.shape

(3, 3)

In [25]:
b.ndim

2

In [26]:
b.size

9

In [27]:
b.itemsize

8

1 dimension to 2 dimension

In [32]:
#reshare
b.reshape(9,1)



array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

3dimensionsal array

In [47]:
d=b.reshape(3,3,1,1)
d


array([[[[1]],

        [[2]],

        [[3]]],


       [[[4]],

        [[5]],

        [[6]]],


       [[[7]],

        [[8]],

        [[9]]]])

In [50]:
oned = b.reshape(-1,1)
oned

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
oned = b.reshape(-1,)
oned

array([1, 2, 3, 4, 5, 6, 7, 8, 9])


**Flatten**

In [52]:
#flatten -->it is used to convert 2d or nd to 1 d
z= np.array([[1,2,3],[4,5,6],[7,8,9]])
flat = z.flatten()
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
flat[0]=10
flat

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [55]:
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Ravel**

In [56]:
#Ravel
z= np.array([[1,2,3],[4,5,6],[7,8,9]])
rav = z.ravel()
rav

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
rav[0]=10
rav

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [60]:
z

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [61]:
#manually creating 2*2
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#arange

In [67]:
#a range to create in different way

a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a1 = np.arange(1,12,2).reshape(3,2)
a1

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

#linspace

In [76]:
a1 = np.linspace(1,10)
a1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [80]:
a1 = np.linspace(1,10,20,retstep=True)
a1

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [81]:
a1 = np.linspace(1,10,20,retstep=True,endpoint=False)
a1

(array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
        5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55]),
 0.45)

#eye---> identity metrix

In [82]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
a=np.eye(3,4,dtype=int)
a


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [88]:
a.dtype

dtype('int64')

In [89]:
a=np.eye(3,4,dtype=int,k=1)
a

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [93]:
r= np.zeros((3,3),dtype=int)  #to get the zeros in 3 row and 3 column it should be in a tuple otherwise there will be error
r

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])