<a href="https://colab.research.google.com/github/shareefat/folio/blob/main/DAV_DAY_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INSERT

In [1]:
import numpy as np
a=np.array([10,11,12,13])
a

array([10, 11, 12, 13])

In [2]:
np.insert(a,0,9)

array([ 9, 10, 11, 12, 13])

In [3]:
a

array([10, 11, 12, 13])

In [6]:
import numpy as np
b=np.array([[10,17,13],
            [20,26,29],
            [41,39,15]])
b

array([[10, 17, 13],
       [20, 26, 29],
       [41, 39, 15]])

#AXIS 1 = COLUMN WISE #--------#AXIS 0 = ROW WISE#--#AXIS=NONE

In [7]:
b.shape

(3, 3)

In [8]:
b.itemsize

8

In [9]:
b.size

9

In [10]:
b=np.insert(b,1,10,axis=1)
b

array([[10, 10, 17, 13],
       [20, 10, 26, 29],
       [41, 10, 39, 15]])

In [11]:
import numpy as np
c=np.array([[10,17,13],
            [20,26,29],
            [41,39,15]])
c

array([[10, 17, 13],
       [20, 26, 29],
       [41, 39, 15]])

In [23]:
c=np.insert(c,0,values=[21,22,23],axis=0)
c

array([21, 22, 23, 21, 22, 23, 21, 22, 23, 21, 22, 23, 21, 22, 23, 21, 27,
       33, 10, 10, 17, 13, 20, 10, 26, 29, 41, 10, 39, 15])

In [14]:
c=np.insert(b,0,values=[21,27,33])
c

array([21, 27, 33, 21, 27, 33, 10, 10, 17, 13, 20, 10, 26, 29, 41, 10, 39,
       15])

In [17]:
q=np.arange(1,10,1).reshape(3,3)
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
import numpy as np
w=np.eye(4)
w

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
import numpy as np
e=np.array([[12,2,3],[4,3,2],[1,2,3]])
e

array([[12,  2,  3],
       [ 4,  3,  2],
       [ 1,  2,  3]])

In [39]:
e=np.array([[12,2,3],[4,3,2],[1,2,3]])
rav=e.ravel()
rav

array([12,  2,  3,  4,  3,  2,  1,  2,  3])

In [40]:
rav[0]=1
rav

array([1, 2, 3, 4, 3, 2, 1, 2, 3])

In [41]:
e

array([[1, 2, 3],
       [4, 3, 2],
       [1, 2, 3]])

In [29]:
e=np.full((3,3),13)
e

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [44]:
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
r=np.array([[2,3,4],[5,6,7],[3,5,7]])
r
np.insert(r,1,10,axis=1)

array([[ 2, 10,  3,  4],
       [ 5, 10,  6,  7],
       [ 3, 10,  5,  7]])

In [47]:
np.insert(r,0,4,axis=0)

array([[4, 4, 4],
       [2, 3, 4],
       [5, 6, 7],
       [3, 5, 7]])

#delete

In [48]:
r
np.delete(r,2,axis=1)

array([[2, 3],
       [5, 6],
       [3, 5]])

In [52]:
l=np.array([[2,3,4],[5,6,7],[3,5,7]])
l
l.reshape(3,3)
np.delete(l,0,axis=0)

array([[5, 6, 7],
       [3, 5, 7]])

In [62]:
l=np.array([[2,3,4],[5,6,7],[3,5,7]])
l
l.reshape(-1,)
np.delete(l,6)

array([2, 3, 4, 5, 6, 7, 5, 7])

#Array concatenate

In [70]:
a=np.arange(1,9,2).reshape(2,2)
b=np.arange(9,17,2).reshape(2,2)
print(a)
print(b)

[[1 3]
 [5 7]]
[[ 9 11]
 [13 15]]


In [64]:
row_concate=np.concatenate((a,b),axis=0)
row_concate

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [ 9, 11],
       [13, 15]])

In [71]:
col_concate=np.concatenate((a,b),axis=1)
col_concate

array([[ 1,  3,  9, 11],
       [ 5,  7, 13, 15]])

In [73]:
none_concate=np.concatenate((a,b),axis=None)
none_concate

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [76]:
c=np.arange(1,10,1).reshape(3,3)
c
d=np.arange(11,20,1).reshape(3,3)
d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [77]:
row=np.vstack((c,d))
row

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [78]:
row=np.hstack((c,d))
row

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [79]:
row=np.dstack((c,d))
row

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

#Split Array

In [89]:
e=np.arange(1,12,2).reshape(3,2)
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [91]:
split2=np.split(e,3)
split2

[array([[1, 3]]), array([[5, 7]]), array([[ 9, 11]])]