<a href="https://colab.research.google.com/github/shareefat/folio/blob/main/DAV_DAY_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#brodcasting

In [ ]:
import numpy as np
a=np.array([[10,18],[20,40]]).reshape(2,2)
a

array([[10, 18],
       [20, 40]])

In [ ]:
import numpy as np
b=np.array([[7,17],[5,30]]).reshape(2,2)
b

array([[ 7, 17],
       [ 5, 30]])

In [ ]:
print("The answer for this array is")
print("")
print("addition  :")
print(a+b)
print("")
print("substracton  :")
print(a-b)
print("")
print("multiplication  :")
print(a*b)
print("")
print("division  :")
print(a/b)

The answer for this array is

addition  :
[[17 35]
 [25 70]]

substracton  :
[[ 3  1]
 [15 10]]

multiplication  :
[[  70  306]
 [ 100 1200]]

division  :
[[1.42857143 1.05882353]
 [4.         1.33333333]]


In [ ]:
c = np.array([[10, 10], [20, 40]])
c
d=np.dot(a,c)
print(d)

[[ 460  820]
 [1000 1800]]


In [ ]:
matrix_a=np.matrix(a)
matrix_b=np.matrix(b)
print(matrix_a)

[[10 18]
 [20 40]]


In [ ]:
lst = np.array([[20,30],[50,1]])
lst


array([[20, 30],
       [50,  1]])

In [ ]:
arr = np.array([[20,30],[50,1]])
arr

array([[20, 30],
       [50,  1]])

In [ ]:
matrixa = np.matrix(lst)
matrixa

matrix([[20, 30],
        [50,  1]])

In [ ]:
matrixa * matrix_b

matrix([[1900,  630],
        [1050, 1501]])

#Linear Algebra

In [ ]:
from numpy import linalg
int,float=5,6.3
print(int,float)

5 6.3


In [ ]:
from numpy import linalg
a=np.arange(1,10).reshape(3,3)
print(a)

determinant=linalg.det(a)
print(determinant)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [39]:
b=np.arange(1,5).reshape(2,2)
b
deteminant = linalg.det(b)
print(deteminant)

-2.0000000000000004


#algibra solving linalg.solve(a,b)

In [42]:
from numpy import linalg
a=np.array([[1,2],[5,1]])
a
b=np.array([7,17])
b

array([ 7, 17])

In [43]:
solve = linalg.solve(a,b)
print(solve)

[3. 2.]


In [47]:
from numpy import linalg
a=np.array([[5,7],[6,2]])
a
b=np.array([55,25])
b

solution=linalg.solve(a,b)
print("the solution is  : ",solution)

the solution is  :  [2.03125 6.40625]


#inverse

In [48]:
from numpy import linalg
a=np.array([[1,5],[10,7]])
a
b=linalg.inv(a)
print("the solution for the question is : ",b)

the solution for the question is :  [[-0.1627907   0.11627907]
 [ 0.23255814 -0.02325581]]


#Transpose ----np.transpose(a) or for array a.T

In [49]:
transpose=np.transpose(a)
print(transpose)

[[ 1 10]
 [ 5  7]]
